In [3]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Day of the Week and Crash Date
data = pd.read_csv("traffic_accidents.csv")

# Convert Crash Day
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')
data['Crash Day'] = data['crash_date'].dt.day_name()

# Unique values for crash day
crash_days = data['Crash Day'].unique().tolist()

results = []
for day in crash_days:
    day_data = data[data['Crash Day'] == day]
    
    total_accident = day_data['injuries_total'].count() 
    min_injury = day_data['injuries_total'].min()  
    max_injury = day_data['injuries_total'].max()  
    avg_injury = day_data['injuries_total'].mean()  
    
    # Append result dictionary for each crash day
    results.append({
        'Crash Day': day,
        'Total Accident': total_accident,
        'Min Injuries Total': min_injury,
        'Max Injuries Total': max_injury,
        'Average Injuries Total': round(avg_injury, 2),
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

,Crash Day,Total Accident,Min Injuries Total,Max Injuries Total,Average Injuries Total
6,Friday,34458,0.0,19.0,0.36
2,Thursday,30787,0.0,13.0,0.36
0,Saturday,30710,0.0,16.0,0.40
3,Wednesday,30093,0.0,21.0,0.38
4,Tuesday,30074,0.0,11.0,0.36
5,Monday,27938,0.0,21.0,0.38
1,Sunday,25246,0.0,12.0,0.45

In [1]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Month
data = pd.read_csv("traffic_accidents.csv")

# Convert Crash Month
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')
data['Crash Month'] = data['crash_date'].dt.month_name()

# Unique values for Crash Month
crash_days = data['Crash Month'].unique().tolist()

results = []
for month in crash_days:
    day_data = data[data['Crash Month'] == month]
    
    total_accident = day_data['injuries_total'].count() 
    max_injury = day_data['injuries_total'].max()  
    avg_injury = day_data['injuries_total'].mean()  
    
    # Append result dictionary for each crash month
    results.append({
        'Crash Month': month,
        'Total Accident': total_accident,
        'Max Injuries Total': max_injury,
        'Average Injuries Total': round(avg_injury, 2)
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

   Crash Month  Total Accident  Max Injuries Total  Average Injuries Total
8      October           20089                21.0                    0.39
3    September           19018                11.0                    0.41
2     December           18816                21.0                    0.36
1       August           18350                15.0                    0.41
5     November           18328                17.0                    0.37
4         June           17851                 9.0                    0.41
0         July           17834                12.0                    0.43
11         May           17432                16.0                    0.40
10     January           16606                 9.0                    0.34
7        March           15265                12.0                    0.36
9        April           15096                15.0                    0.38
6     February           14621                19.0                    0.32

In [9]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Year
data = pd.read_csv("traffic_accidents.csv")

# Convert Crash Year
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')
data['Crash Year'] = data['crash_date'].dt.year

# Unique values for Crash Year
crash_days = data['Crash Year'].unique().tolist()

results = []
for year in crash_days:
    day_data = data[data['Crash Year'] == year]
    
    total_accident = day_data['injuries_total'].count() 
    max_injury = day_data['injuries_total'].max()  
    avg_injury = day_data['injuries_total'].mean()  
    
    # Append result dictionary for each crash month
    results.append({
        'Crash Year': year,
        'Total Accident': total_accident,
        'Max Injuries Total': max_injury,
        'Average Injuries Total': round(avg_injury, 2)
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Crash Year', ascending=True)
res_df

    Crash Year  Total Accident  Max Injuries Total  Average Injuries Total
10        2013               2                 2.0                    1.50
7         2015            1917                 5.0                    0.15
4         2016            7615                13.0                    0.18
8         2017           17655                11.0                    0.33
3         2018           27438                21.0                    0.37
6         2019           27959                16.0                    0.36
5         2020           22784                19.0                    0.41
1         2021           25689                21.0                    0.40
2         2022           25543                17.0                    0.40
0         2023           25454                11.0                    0.41
9         2024           26214                15.0                    0.44
11        2025            1036                 7.0                    0.40

In [7]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Day Name and Time Period
data = pd.read_csv("traffic_accidents.csv")

# Convert Crash Date
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')

# Extract Day Name and Time Period (AM/PM)
data['Day Name'] = data['crash_date'].dt.day_name()
data['Time Period'] = data['crash_date'].dt.strftime('%p')

# Combine Day Name and Time Period
data['Day-Time Period'] = data['Day Name'] + ' - ' + data['Time Period']

# Unique values for Day-Time Period
day_time_groups = data['Day-Time Period'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Day-Time Period'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    max_injury = group_data['injuries_total'].max()  
    avg_injury = group_data['injuries_total'].mean()  
    
    # Append result dictionary for each Day-Time Period
    results.append({
        'Day-Time Period': group,
        'Total Accident': total_accident,
        'Max Injuries Total': max_injury,
        'Average Injuries Total': round(avg_injury, 2)
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

   Day-Time Period  Total Accident  Max Injuries Total  Average Injuries Total
10     Friday - PM           23643                15.0                    0.35
0    Saturday - PM           20704                16.0                    0.38
7    Thursday - PM           20193                13.0                    0.36
9     Tuesday - PM           19537                11.0                    0.37
3   Wednesday - PM           19471                17.0                    0.37
6      Monday - PM           17806                 9.0                    0.37
8      Sunday - PM           15469                 9.0                    0.42
11     Friday - AM           10815                19.0                    0.38
4   Wednesday - AM           10622                21.0                    0.38
2    Thursday - AM           10594                 9.0                    0.36
5     Tuesday - AM           10537                 8.0                    0.36
13     Monday - AM           10132                21.0                    0.39
12   Saturday - AM           10006                12.0                    0.45
1      Sunday - AM            9777                12.0                    0.50

In [11]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Day Name and Is Injured
data = pd.read_csv("traffic_accidents.csv")

# Convert Crash Date
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')

# Extract Day Name
data['Day Name'] = data['crash_date'].dt.day_name()

# Categorize Injured
def categorize_injured(val):
    if val == 0:
        return "No Injured"
    else:
        return "Injured"

# Group by Injured and Count
data['is_injured'] = data['injuries_total'].apply(categorize_injured)

# Combine Day Name and Is Injured
data['Day-Is Injured'] = data['Day Name'] + ' - ' + data['is_injured']

# Unique values for Day-Is Injured
day_time_groups = data['Day-Is Injured'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Day-Is Injured'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Day-Is Injured
    results.append({
        'Day-Is Injured': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

            Day-Is Injured  Total Accident
8      Friday - No Injured           25988
2    Thursday - No Injured           22867
0    Saturday - No Injured           22649
4     Tuesday - No Injured           22339
6   Wednesday - No Injured           22291
5      Monday - No Injured           20632
1      Sunday - No Injured           18023
12        Friday - Injured            8470
13      Saturday - Injured            8061
9       Thursday - Injured            7920
3      Wednesday - Injured            7802
7        Tuesday - Injured            7735
11        Monday - Injured            7306
10        Sunday - Injured            7223

In [9]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Time of Day and Is Intersection Related
data = pd.read_csv("traffic_accidents.csv")

# Extract Day and Hour from crash_date
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')
data['day'] = data['crash_date'].dt.day_name()
data['hour'] = data['crash_date'].dt.hour

# Categorize hour into time periods
def categorize_time(hour):
    if 0 <= hour <= 5:
        return "Midnight"
    elif 6 <= hour <= 11:
        return "Morning"
    elif 12 <= hour <= 17:
        return "Evening"
    elif 18 <= hour <= 23:
        return "Night"

data['time'] = data['hour'].apply(categorize_time)

# Combine Time and Is Intersection Related
data['Time-Is Intersection Related'] = data['time'] + ' - ' + data['intersection_related_i']

# Unique values for Time-Is Intersection Related
day_time_groups = data['Time-Is Intersection Related'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Time-Is Intersection Related'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Day-Is Injured
    results.append({
        'Day-Is Intersection Related': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

  Day-Is Intersection Related  Total Accident
0                 Evening - Y           81143
2                 Morning - Y           51447
3                   Night - Y           49233
1                Midnight - Y           17501
6                 Evening - N            3897
5                   Night - N            2550
7                 Morning - N            2453
4                Midnight - N            1082

In [3]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Day Type and Is Intersection Related
data = pd.read_csv("traffic_accidents.csv")

# Categorize Day
def categorize_day(day):
    if day <= 5:
        return "Weekday"
    else:
        return "Weekend"

# Group by Period and Count
data['crash_day_week_type'] = data['crash_day_of_week'].apply(categorize_day)

# Combine Day Type and Is Intersection Related
data['Day Type-Is Intersection Related'] = data['crash_day_week_type'] + ' - ' + data['intersection_related_i']

# Unique values for Day Type-Is Intersection Related
day_time_groups = data['Day Type-Is Intersection Related'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Day Type-Is Intersection Related'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Day-Is Injured
    results.append({
        'Day Type-Is Intersection Related': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

  Day Type-Is Intersection Related  Total Accident
1                      Weekday - Y          137318
0                      Weekend - Y           62006
2                      Weekday - N            6820
3                      Weekend - N            3162

In [11]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Weather Condition, Roadway Surface Condition and Is Intersection Related
data = pd.read_csv("traffic_accidents.csv")

target_col = ['roadway_surface_cond','weather_condition']

for dt in target_col:
    col_clean = dt.replace("_"," ").title()
    # Combine Weather Condition, Roadway Surface Condition and Is Intersection Related
    data[f'{col_clean}-Is Intersection Related'] = data[dt] + ' - ' + data['intersection_related_i']
    
    # Unique values for Weather Condition, Roadway Surface Condition-Is Intersection Related
    day_time_groups = data[f'{col_clean}-Is Intersection Related'].unique().tolist()
    
    results = []
    for group in day_time_groups:
        group_data = data[data[f'{col_clean}-Is Intersection Related'] == group]
        
        total_accident = group_data['injuries_total'].count() 
        
        # Append result dictionary for each Weather Condition, Roadway Surface Condition-Is Injured
        results.append({
            f'{col_clean}-Is Intersection Related': group,
            'Total Accident': total_accident
        })
    
    # Sort
    res_df = pd.DataFrame(results)
    res_df = res_df.sort_values(by='Total Accident', ascending=False)
    print(res_df)
    print("\n")

   Roadway Surface Cond-Is Intersection Related  Total Accident
1                                       DRY - Y          148485
3                                       WET - Y           31463
0                                   UNKNOWN - Y           11822
5                                       DRY - N            7420
4                             SNOW OR SLUSH - Y            5871
2                                       WET - N            1445
6                                       ICE - Y            1229
11                                  UNKNOWN - N             687
7                                     OTHER - Y             417
8                             SNOW OR SLUSH - N             332
12                                      ICE - N              74
9                           SAND, MUD, DIRT - Y              37
10                                    OTHER - N              21
13                          SAND, MUD, DIRT - N               3


   Weather Condition-Is Intersection Related  Total Accident
0                                  CLEAR - Y          156797
2                                   RAIN - Y           20759
4                                  CLEAR - N            7903
5                        CLOUDY/OVERCAST - Y            7235
3                                   SNOW - Y            6521
6                                UNKNOWN - Y            6162
1                                   RAIN - N             944
11                                 OTHER - Y             587
10                 FREEZING RAIN/DRIZZLE - Y             475
9                                UNKNOWN - N             372
12                                  SNOW - N             350
7                         FOG/SMOKE/HAZE - Y             343
14                       CLOUDY/OVERCAST - N             298
13                            SLEET/HAIL - Y             295
8                           BLOWING SNOW - Y             119
15                                 OTHER - N              40
16                 FREEZING RAIN/DRIZZLE - N              35
17                SEVERE CROSS WIND GATE - Y              30
20                        FOG/SMOKE/HAZE - N              17
19                            SLEET/HAIL - N              13
21                          BLOWING SNOW - N               8
22                SEVERE CROSS WIND GATE - N               2
18              BLOWING SAND, SOIL, DIRT - Y               1

In [17]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Intersection Related and Is Injured
data = pd.read_csv("traffic_accidents.csv")

# Categorize Injured
def categorize_injured(val):
    if val == 0:
        return "No Injured"
    else:
        return "Injured"

# Group by Injured and Count
data['is_injured'] = data['injuries_total'].apply(categorize_injured)

# Combine Intersection Related and Is Injured
data['Intersection Related-Is Injured'] = data['intersection_related_i'] + ' - ' + data['is_injured']

# Unique values for Intersection Related-Is Injured
day_time_groups = data['Intersection Related-Is Injured'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Intersection Related-Is Injured'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Intersection Related-Is Injured
    results.append({
        'Intersection Related-Is Injured': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

  Intersection Related-Is Injured  Total Accident
0                  Y - No Injured          146794
1                     Y - Injured           52530
3                  N - No Injured            7995
2                     N - Injured            1987

In [5]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Intersection Related and Is Fatal Injured
data = pd.read_csv("traffic_accidents.csv")

# Categorize Fatal Injured
def categorize_injured(val):
    if val == 0:
        return "No Fatal Injured"
    else:
        return "Fatal Injured"

# Group by Fatal Injured and Count
data['is_fatal_injured'] = data['injuries_fatal'].apply(categorize_injured)

# Combine Intersection Related and Is Fatal Injured
data['Intersection Related-Is Fatal Injured'] = data['intersection_related_i'] + ' - ' + data['is_fatal_injured']

# Unique values for Intersection Related-Is Fatal Injured
day_time_groups = data['Intersection Related-Is Fatal Injured'].unique().tolist()

results = []
for group in day_time_groups:
    group_data = data[data['Intersection Related-Is Fatal Injured'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Intersection Related-Is Fatal Injured
    results.append({
        'Intersection Related-Is Fatal Injured': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Total Accident', ascending=False)
res_df

  Intersection Related-Is Fatal Injured  Total Accident
0                  Y - No Fatal Injured          198999
1                  N - No Fatal Injured            9956
2                     Y - Fatal Injured             325
3                     N - Fatal Injured              26

In [15]:
import pandas as pd
import statistics
import numpy as np

# Declaration
# Descriptive Statistic for Analyzed Accidents by Crash Year and Is Injured
data = pd.read_csv("traffic_accidents.csv")

# Categorize Injured
def categorize_injured(val):
    if val == 0:
        return "No Injured"
    else:
        return "Injured"

# Group by Injured and Count
data['is_injured'] = data['injuries_total'].apply(categorize_injured)

# Convert Crash Year
data['crash_date'] = pd.to_datetime(data['crash_date'], format='%m/%d/%Y %I:%M:%S %p')
data['Crash Year'] = data['crash_date'].dt.year

# Combine Crash Year and Is Injured (fixed)
data['Crash Year-Is Injured'] = data['Crash Year'].astype(str) + " - " + data['is_injured']

# Unique values for Crash Year-Is Injured
day_time_groups = data['Crash Year-Is Injured'].unique().tolist()

# Calculate Total Accident for Each Group
results = []
for group in day_time_groups:
    group_data = data[data['Crash Year-Is Injured'] == group]
    
    total_accident = group_data['injuries_total'].count() 
    
    # Append result dictionary for each Crash Year-Is Injured
    results.append({
        'Crash Year-Is Injured': group,
        'Total Accident': total_accident
    })

# Sort
res_df = pd.DataFrame(results)
res_df = res_df.sort_values(by='Crash Year-Is Injured', ascending=True)
res_df

   Crash Year-Is Injured  Total Accident
20        2013 - Injured               2
17        2015 - Injured             214
12     2015 - No Injured            1703
16        2016 - Injured             936
5      2016 - No Injured            6679
15        2017 - Injured            4025
14     2017 - No Injured           13630
11        2018 - Injured            7097
4      2018 - No Injured           20341
7         2019 - Injured            7030
9      2019 - No Injured           20929
10        2020 - Injured            6248
6      2020 - No Injured           16536
13        2021 - Injured            6926
1      2021 - No Injured           18763
8         2022 - Injured            6984
3      2022 - No Injured           18559
2         2023 - Injured            7046
0      2023 - No Injured           18408
19        2024 - Injured            7731
18     2024 - No Injured           18483
22        2025 - Injured             278
21     2025 - No Injured             758